dataset:
  train:  # LMDB
    type: LinearDataset

    # for lmdb
    root: /
    gt_folder: data1/360Enhance/train_data/raw/
    lq_folder: data/360Enhance/train_set/com/qp22/

    # for dataset
    # use the absolute path
    gt_path: /data/360Enhance/train_set/lmdb/clip_qp22/VQA_train_gt.lmdb
    lq_path: /data/360Enhance/train_set/lmdb/clip_qp22/VAQ_train_lq.lmdb
    meta_info_fp: meta_info.txt
    gt_size: 96  # ground truth patch size: gt_size * gt_size
    use_flip: True
    use_rot: True  # rotation per 90 degrees
    random_reverse: False

    # for datasampler
    enlarge_ratio: 1  # enlarge dataset by randomly cropping.

    # for dataloader
    num_worker_per_gpu: 24  # 12 in total. mainly affect IO speed
    batch_size_per_gpu: 32  # bs=32, divided by 4 GPUs
#    num_worker_per_gpu: 1  # 12 in total. mainly affect IO speed
#    batch_size_per_gpu: 1  # bs=32, divided by 4 GPUs

  val:  # Disk IO
    type: VideoTestMFQEv2Dataset
    #root: /media/x/Database/MFQEv2/
    # use the absolute path
    gt_path: /data/360Enhance/train_set/com/qp22/
    lq_path: /data1/360Enhance/train_data/raw/
    #meta_info_fp: meta_info.txt
    #enlarge_ratio: 1
    #use_flip: False
    #use_rot: False
    #random_reverse: False

  test:
    type: VideoTestMFQEv2Dataset
    gt_path: raw_video/
    lq_path: com_video/

network:
  radius: 3  # total num of input frame = 2 * radius + 1

  stdf:
    in_nc: 1  # 1 for Y
    out_nc: 64
    nf: 32  # num of feature maps
    nb: 3  # num of conv layers
    base_ks: 3
    deform_ks: 3  # size of the deformable kernel
    load_path: baseline_model_path

  qenet:
    in_nc: 64  # = out_nc of stdf
    out_nc: 1  # 1 for Y
    nf: 48
    nb: 8
    base_ks: 3

train:
  exp_name: selector_22_normalize100_L2 # default: timestr. None: ~
  random_seed: 7
  pre-val: False  # evaluate criterion before training, e.g., ori PSNR
  num_iter: !!float 1e+3
  interval_print: !!float 10
  interval_val: !!float 1e+2  # also save model
  pbar_len: 100

  optim:
    type: Adam
    lr: !!float 1e-3  # init lr of scheduler
    betas: [0.9, 0.999]
    eps: !!float 1e-08

  scheduler:
    is_on: False
    type: CosineAnnealingRestartLR
    periods: [!!float 5e+4, !!float 5e+4, !!float 5e+4, !!float 5e+4, !!float 5e+4, !!float 5e+4]  # epoch interval
    restart_weights: [1, 0.5, 0.5, 0.5, 0.5, 0.5]
    eta_min: !!float 1e-7

  loss:
    type: CharbonnierLoss
    eps: !!float 1e-6

  criterion:
    type: PSNR
    unit: dB

test:
  restore_iter: !!float 290000
  pbar_len: 100

  criterion:
    type: PSNR
    unit: dB
